Repository stolostron/hub-of-hubs-manager, pull requests merged in 2022-05, with the labels that each got.

#4 [WIP]add spec transport bridge.
  README.md
  cmd/manager/main.go
  deploy/operator.yaml.template
  go.mod
  go.sum
  pkg/bundle/base_objects_bundle.go
  pkg/bundle/objects_bundle.go
  pkg/db/db.go
  pkg/db/postgresql/postgresql.go
  pkg/dbsyncers/dbsyncers.go
  pkg/intervalpolicy/exponential_backoff_policy.go
  pkg/intervalpolicy/interval_policy.go
  pkg/scheme/scheme.go
  pkg/specsyncer/dbtotransport/controllers.go
  pkg/specsyncer/dbtotransport/statuswatcher/managed_cluster_labels_status_watcher.go
  pkg/specsyncer/dbtotransport/transportsyncer/applications_db_to_transport_syncer.go
  pkg/specsyncer/dbtotransport/transportsyncer/channels_db_to_transport_syncer.go
  pkg/specsyncer/dbtotransport/transportsyncer/generic_db_to_transport_syncer.go
  pkg/specsyncer/dbtotransport/transportsyncer/helpers.go
  pkg/specsyncer/dbtotransport/transportsyncer/hoh_config_db_to_transport_syncer.go
  pkg/specsyncer/dbtotransport/transportsyncer/managed_cluster_labels_db_to_transport_syncer.go
  pkg/specsyncer/dbtotransport/transportsyncer/managed_cluster_set_bindings_db_to_transport_syncer.go
  pkg/specsyncer/dbtotransport/transportsyncer/managed_cluster_sets_db_to_transport_syncer.go
  pkg/specsyncer/dbtotransport/transportsyncer/placementbindings_db_to_transport_syncer.go
  pkg/specsyncer/dbtotransport/transportsyncer/placementrules_db_to_transport_syncer.go
  pkg/specsyncer/dbtotransport/transportsyncer/placements_db_to_transport_syncer.go
  pkg/specsyncer/dbtotransport/transportsyncer/policies_db_to_transport_syncer.go
  pkg/specsyncer/dbtotransport/transportsyncer/subscriptions_db_to_transport_syncer.go
  pkg/specsyncer/spectodb/controller/application_spec_sync.go
  pkg/specsyncer/spectodb/controller/channel_spec_sync.go
  pkg/specsyncer/spectodb/controller/generic_spec_to_db_reconciler.go
  pkg/specsyncer/spectodb/controller/hoh_config_spec_sync.go
  pkg/specsyncer/spectodb/controller/managedclusterset_spec_sync.go
  pkg/specsyncer/spectodb/controller/managedclustersetbinding_spec_sync.go
  pkg/specsyncer/spectodb/controller/placement_spec_sync.go
  pkg/specsyncer/spectodb/controller/placementbinding_spec_sync.go
  pkg/specsyncer/spectodb/controller/placementrule_spec_sync.go
  pkg/specsyncer/spectodb/controller/policy_spec_sync.go
  pkg/specsyncer/spectodb/controller/subscription_spec_sync.go
  pkg/specsyncer/spectodb/controllers.go
  pkg/statussyncer/dbtostatus/dbsyncer/policy_syncer.go
  pkg/statussyncer/dbtostatus/dbsyncers.go
  pkg/transport/compressor/compressor.go
  pkg/transport/compressor/gzip_compressor.go
  pkg/transport/compressor/no_op_compressor.go
  pkg/transport/kafka/producer.go
  pkg/transport/syncservice/syncservice.go
  pkg/transport/transport.go
  pkg/transport/transport_message.go
Labels: approved, do-not-merge/work-in-progress

#7 remove legacy compression.
  go.mod
  go.sum
  pkg/statussyncer/transport2db/transport/kafka/consumer.go
  pkg/statussyncer/transport2db/transport/syncservice/sync_service.go
Labels: approved

#8 add config api.
  Makefile
  deploy/cr-examples/hub-of-hubs.open-cluster-management.io_config_cr.yaml
  deploy/crd/hub-of-hubs.open-cluster-management.io_configs.yaml
  go.mod
  go.sum
  hack/boilerplate.go.txt
  pkg/apis/config/v1/config_types.go
  pkg/apis/config/v1/register.go
  pkg/apis/config/v1/zz_generated.deepcopy.go
  pkg/bundle/spec/managed_clusters_labels_bundle.go
  pkg/bundle/status/base_compliance_status_bundle.go
  pkg/bundle/status/base_minimal_compliance_status_bundle.go
  pkg/bundle/status/bundle_sync_mode.go
  pkg/bundle/status/bundle_version.go
  pkg/constants/constants.go
  pkg/scheme/scheme.go
  pkg/specsyncer/db2transport/bundle/base_objects_bundle.go
  pkg/specsyncer/db2transport/db/db.go
  pkg/specsyncer/db2transport/db/postgresql/postgresql.go
  pkg/specsyncer/db2transport/syncer/dbsyncer/helpers.go
  pkg/specsyncer/db2transport/syncer/dbsyncer/hoh_config_db_to_transport_syncer.go
  pkg/specsyncer/db2transport/syncer/dbsyncer/managed_cluster_labels_db_to_transport_syncer.go
  pkg/specsyncer/spec2db/controller/hoh_config_spec_sync.go
  pkg/statussyncer/transport2db/bundle/base_bundle.go
  pkg/statussyncer/transport2db/bundle/bundle.go
  pkg/statussyncer/transport2db/bundle/clusters_per_policy_bundle.go
  pkg/statussyncer/transport2db/bundle/complete_compliance_status_bundle.go
  pkg/statussyncer/transport2db/bundle/delta_compliance_status_bundle.go
  pkg/statussyncer/transport2db/bundle/minimal_compliace_status_bundle.go
  pkg/statussyncer/transport2db/conflator/bundle_metadata.go
  pkg/statussyncer/transport2db/conflator/conflation_element.go
  pkg/statussyncer/transport2db/conflator/conflation_registration.go
  pkg/statussyncer/transport2db/conflator/conflation_unit.go
  pkg/statussyncer/transport2db/conflator/delta_state_bundle_info.go
  pkg/statussyncer/transport2db/syncer/config/config_controller.go
  pkg/statussyncer/transport2db/syncer/dbsyncer/control_info_db_syncer.go
  pkg/statussyncer/transport2db/syncer/dbsyncer/generic_db_syncer.go
  pkg/statussyncer/transport2db/syncer/dbsyncer/local_spec_db_syncer.go
  pkg/statussyncer/transport2db/syncer/dbsyncer/managed_clusters_db_syncer.go
  pkg/statussyncer/transport2db/syncer/dbsyncer/placement_decisions_db_syncer.go
  pkg/statussyncer/transport2db/syncer/dbsyncer/placement_rules_db_syncer.go
  pkg/statussyncer/transport2db/syncer/dbsyncer/placements_db_syncer.go
  pkg/statussyncer/transport2db/syncer/dbsyncer/policies_db_syncer.go
  pkg/statussyncer/transport2db/syncer/dbsyncer/subscription_reports_db_syncer.go
  pkg/statussyncer/transport2db/syncer/dbsyncer/subscription_statuses_db_syncer.go
  pkg/statussyncer/transport2db/syncer/syncers.go
  pkg/statussyncer/transport2db/transport/syncservice/sync_service.go
Labels: approved

#9 update deploy.
  README.md
  deploy/operator.yaml.template
Labels: approved

#11 rebase latest changes.
  deploy/operator.yaml.template
  go.mod
  go.sum
  pkg/bundle/status/base_minimal_compliance_status_bundle.go
  pkg/nonk8sapi/managedclusters/list.go
  pkg/scheme/scheme.go
  pkg/specsyncer/db2transport/syncer/dbsyncer/applications_db_to_transport_syncer.go
  pkg/specsyncer/db2transport/syncer/dbsyncer/channels_db_to_transport_syncer.go
  pkg/specsyncer/db2transport/syncer/dbsyncer/placementbindings_db_to_transport_syncer.go
  pkg/specsyncer/db2transport/syncer/dbsyncer/placementrules_db_to_transport_syncer.go
  pkg/specsyncer/db2transport/syncer/dbsyncer/placements_db_to_transport_syncer.go
  pkg/specsyncer/db2transport/syncer/dbsyncer/policies_db_to_transport_syncer.go
  pkg/specsyncer/db2transport/syncer/dbsyncer/subscriptions_db_to_transport_syncer.go
  pkg/specsyncer/db2transport/transport/syncservice/syncservice.go
  pkg/specsyncer/spec2db/controller/application_spec_sync.go
  pkg/specsyncer/spec2db/controller/channel_spec_sync.go
  pkg/specsyncer/spec2db/controller/generic_spec_to_db_reconciler.go
  pkg/specsyncer/spec2db/controller/hoh_config_spec_sync.go
  pkg/specsyncer/spec2db/controller/managedclusterset_spec_sync.go
  pkg/specsyncer/spec2db/controller/managedclustersetbinding_spec_sync.go
  pkg/specsyncer/spec2db/controller/placement_spec_sync.go
  pkg/specsyncer/spec2db/controller/placementbinding_spec_sync.go
  pkg/specsyncer/spec2db/controller/placementrule_spec_sync.go
  pkg/specsyncer/spec2db/controller/policy_spec_sync.go
  pkg/specsyncer/spec2db/controller/subscription_spec_sync.go
  pkg/statussyncer/db2status/dbsyncer/consts.go
  pkg/statussyncer/db2status/dbsyncer/generic_db_syncer.go
  pkg/statussyncer/db2status/dbsyncer/helpers.go
  pkg/statussyncer/db2status/dbsyncer/placement_syncer.go
  pkg/statussyncer/db2status/dbsyncer/placementdecision_syncer.go
  pkg/statussyncer/db2status/dbsyncer/placementrule_syncer.go
  pkg/statussyncer/db2status/dbsyncer/policy_syncer.go
  pkg/statussyncer/db2status/dbsyncer/subscription_report_syncer.go
  pkg/statussyncer/db2status/dbsyncer/subscription_status_syncer.go
  pkg/statussyncer/db2status/dbsyncers.go
  pkg/statussyncer/transport2db/bundle/local_placement_rules_bundle.go
  pkg/statussyncer/transport2db/bundle/local_policy_spec_bundle.go
  pkg/statussyncer/transport2db/bundle/managed_clusters_bundle.go
  pkg/statussyncer/transport2db/bundle/placement_decisions_bundle.go
  pkg/statussyncer/transport2db/bundle/placement_rules_bundle.go
  pkg/statussyncer/transport2db/bundle/placements_bundle.go
  pkg/statussyncer/transport2db/db/db.go
  pkg/statussyncer/transport2db/db/postgresql/postgresql.go
  pkg/statussyncer/transport2db/syncer/dbsyncer/generic_db_syncer.go
  pkg/statussyncer/transport2db/syncer/dbsyncer/local_spec_db_syncer.go
  pkg/statussyncer/transport2db/syncer/dbsyncer/managed_clusters_db_syncer.go
Labels: approved

#12 update docker registry.
  Makefile
  README.md
Labels: approved

#13 create hohmanagerconfig.
  cmd/manager/main.go
Labels: approved

#14 replace environment variables with command parameters.
  README.md
  cmd/manager/main.go
  deploy/operator.yaml.template
  pkg/nonk8sapi/non_k8s_api.go
  pkg/specsyncer/db2transport/transport/kafka/producer.go
  pkg/specsyncer/db2transport/transport/syncservice/syncservice.go
  pkg/statistics/statistics.go
  pkg/statussyncer/transport2db/transport/kafka/committer.go
  pkg/statussyncer/transport2db/transport/kafka/consumer.go
  pkg/statussyncer/transport2db/transport/syncservice/committer.go
  pkg/statussyncer/transport2db/transport/syncservice/sync_service.go
Labels: approved, lgtm

#16 Update to use label for local-resource
  pkg/specsyncer/db2transport/db/postgresql/postgresql.go
Labels: approved, lgtm

#15 Update policy status placement
  OWNERS
  cmd/manager/main.go
  pkg/constants/constants.go
  pkg/specsyncer/spec2db/controller/placementbinding_spec_sync.go
  pkg/specsyncer/spec2db/controller/placementrule_spec_sync.go
  pkg/specsyncer/spec2db/controller/policy_spec_sync.go
  pkg/statussyncer/status/controller/placementbinding_controller.go
  pkg/statussyncer/status/controllers.go
Labels: approved, lgtm

#17 Update OWNERS
  OWNERS
Labels: approved, lgtm

#18 expose transport type.
  README.md
  deploy/operator.yaml.template
Labels: approved, lgtm

#19 Correct the query
  pkg/nonk8sapi/managedclusters/patch.go
Labels: approved, lgtm

#20 Add non k8s api for policy
  .gitignore
  cmd/manager/main.go
  go.mod
  pkg/nonk8sapi/non_k8s_api.go
  pkg/nonk8sapi/policies/list_status.go
  pkg/statussyncer/status/controller/placementbinding_controller.go
Labels: approved, lgtm
